### PR TITLE
adding parser for PAGE xml format

### PR DESCRIPTION
**Pull request by alix-tz**
cf. #3 

I tested applying `chocomufin generate`, `chocomufin control` and `chocomufin convert` to PAGE XML files. It works without issue. 

Left to do: add test files (but I need pointers for that).

### CODE REVIEW

**Comment by alix-tz** [comment]
I don't know if Chocomufin should be made compatible with other Page XML Schema version.

**Comment by alix-tz** [comment]
> I don't know if Chocomufin should be made compatible with other Page XML Schema version.

~~Following our discussion today: `.findall()` is most certainly enough to fetch the textline while not having to deal with PAGE's schemas.~~

EDIT: this is done.

**Comment by PonteIneptique** [comment]
@alix-tz We agree that we should have test right ?

**Comment by alix-tz** [comment]
yes! I can't believe it's already been 3 weeks! :o

**Comment by alix-tz** [comment]
I have two questions for you at this point:
- are the if/elif conditions ok in the test file or should we have a AltoTestCase only testing Alto scenarios and PageTestCase only testing Page scenarios? In both cases there would be repetitions
- ~~in HTRVX, test.yml runs something like `nose2 -s ./tests --coverage=chocomufin --coverage-report xml  --verbose` in stead of `nosetests --with-doctest --with-coverage --cover-package=chocomufin --verbose --verbose .`. I can locally run the former but not the latter\*. Is one preferable to the other?~~
- is it ok to remove `test_translator.py` at this point, since I moved the tests it contains in `test_main.py`?

I'll work on #15 when this is delt with so I can write the corresponding test.

\*I get a `AttributeError: module 'collections' has no attribute 'Callable'` error that I didn't investigate further.

**Comment by PonteIneptique** [comment]
> *I get a AttributeError: module 'collections' has no attribute 'Callable' error that I didn't investigate further.

We should run with pytest, because nose is not maintained anymore. I move some projects to this, such as Pyrrha
```yml
 #...
        pip install pytest pytest-cov
        pip install coveralls
        pip install flake8
#    - name: Lint with flake8
#      run: |
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with PyTest
      run: |
        pytest --doctest-modules --cov=app --verbose
```

> are the if/elif conditions ok in the test file or should we have a AltoTestCase only testing Alto scenarios and PageTestCase only testing Page scenarios? In both cases there would be repetitions

We should have a base case that is then extended to different parsers, the same way HTRVX is done if I remember correctly

> is it ok to remove test_translator.py at this point, since I moved the tests it contains in test_main.py?

Sure, or move it to something like `test_workflow.py`

**Comment by PonteIneptique** [comment]
For (2):

```py
class AltoTestCase(TestCase):
     FOLDER = "alto"
     # Test the things


class PageTestCase(AltoTestCase):
    FOLDER = "page"
```

**Comment by alix-tz** [comment]
> For (2):
> 
> ```python
> class AltoTestCase(TestCase):
>      FOLDER = "alto"
>      # Test the things
> 
> 
> class PageTestCase(AltoTestCase):
>     FOLDER = "page"
> ```

so that's what I used, following the example of HTRVX, but there are moments where we need to change the parser too:
- case1: https://github.com/alix-tz/choco-mufin/blob/b042acf77bb7f9f13d6a4899a179aced130b22f1/tests/test_main.py#L55
- case2: https://github.com/alix-tz/choco-mufin/blob/b042acf77bb7f9f13d6a4899a179aced130b22f1/tests/test_main.py#L74

case2 is easy to fix by adding another constant (PARSER = Page, for example), but I guess I don't know how to smoothly fix case1 unless by using an if/else condition.

**Comment by alix-tz** [comment]
My bad, case1 is solvable exactly the same way. Is it ok then to imagine having this?

```
class AltoTestCase(TestCase):
     FOLDER = "alto"
     PARSER = Alto
     # Test the things


class PageTestCase(AltoTestCase):
    FOLDER = "page"
    PARSER = Page
```

**Comment by alix-tz** [comment]
I'm asking in case it's not good practice

**Pull request closed without merging**
